name : 'Terraform 2'

on:
  workflow_dispatch:
    # inputs:
    #   region-value:
    #     # Friendly description to be shown in the UI instead of 'name'
    #     description: 'enter region'
    #     # Default value if no value is explicitly provided
    #     # default: ''u-east-1
    #     # Input has to be provided for the workflow to run
    #     required: true
  # push:
  #   branches: [ "main" ]

env:
  REGION: eu-central-1
  BUCKET: vpc-ec2bucket
  TFSTATE_FILE: new.tfstate eu
  DB_TABLE: vpc-ec2

jobs:
  terraform:
    name: Terraform
    runs-on:  ubuntu-latest

    

    defaults:
      run:
        working-directory: ./example/

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:      ${{ secrets.AWS_SESSION_TOKEN }} add token in secrets

          aws-region: ${{ env.REGION }}                         #${{ github.event.inputs.region-value }}      

      - name: Terraform Init
        id: init
        run:
          terraform init -reconfigure
         -backend-config="bucket=$BUCKET" 
         -backend-config="key=$TFSTATE_FILE" 
         -backend-config="dynamodb_table=$DB_TABLE"
         

      - name: Terraform destroy
        id: destroy
        run:  terraform destroy -auto-approve